version: '6'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/product_catalog"
      SQLALCHEMY_DATABASE_URI: "sqlite:///site.db"

  mongo:
    image: "mongo:latest"
